#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

decomposePar
mpirun -np 32 dissolGravityFoam -parallel 
reconstructPar -newTimes 



# ----------------------------------------------------------------- end-of-file
